version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: guiaDePerguntas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: welcome1
      MYSQL_DATABASE: guiaDePerguntas_db
      MYSQL_USER: node
      MYSQL_PASSWORD: welcome1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: guiaDePerguntas-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data:
